TARGET  = TurboPDF.tpd
OBJECTS = tpd.o
SRCDIRS = .
INCDIRS = .

# MorphOS cross-compiler
CC      = ppc-morphos-gcc
LD      = ppc-morphos-gcc
AR      = ppc-morphos-ar

# Toggle DEBUG via:  make debug=1
ifeq ($(debug),1)
 DIR = build-debug
 CFLAGS_EXTRA = -g -O0 -DDEBUG
 LDFLAGS_EXTRA =
else
 DIR = build-release
 CFLAGS_EXTRA = -s -O2
 LDFLAGS_EXTRA = -s
endif

# libharu linkage via:  make static=0   (default: static from submodule)
#   static   -- build bundled external/libharu submodule and link statically
#   dynamic  -- link against the MorphOS system hpdf.library
ifeq ($(static),0)
 HARU = dynamic
else
 HARU = static
endif

ifeq ($(HARU),static)
 INCDIRS += external/libharu/include
endif

CFLAGS  = -mcpu=750 -Wall -Wextra -Wno-unused-parameter \
          -fomit-frame-pointer -nostartfiles \
          $(addprefix -I,$(INCDIRS)) $(CFLAGS_EXTRA)

LDFLAGS = -mcpu=750 -nostartfiles -Wl,--strip-all \
          $(LDFLAGS_EXTRA)

OBJS    = $(addprefix $(DIR)/,$(OBJECTS))

# -------------------------------------------------------------------
#  Bundled libharu (git submodule: external/libharu)
# -------------------------------------------------------------------
LIBHARU_DIR      = external/libharu
LIBHARU_SRCDIR   = $(LIBHARU_DIR)/src
LIBHARU_BUILDDIR = $(DIR)/libharu
LIBHARU_LIB      = $(LIBHARU_BUILDDIR)/libhpdf.a
LIBHARU_INC      = $(LIBHARU_BUILDDIR)/include
LIBHARU_SRCS     = $(wildcard $(LIBHARU_SRCDIR)/*.c)
LIBHARU_OBJS     = $(patsubst $(LIBHARU_SRCDIR)/%.c,$(LIBHARU_BUILDDIR)/%.o,$(LIBHARU_SRCS))

# generated hpdf_config.h (no optional png/zlib support -> self-contained)
LIBHARU_CONFIG   = $(LIBHARU_INC)/hpdf_config.h

ifeq ($(HARU),static)
 INCDIRS    += $(LIBHARU_INC)
 LINK_LIBHARU = $(LIBHARU_LIB)
 LINK_HPDF    =
else
 LINK_LIBHARU =
 LINK_HPDF    = -lhpdf
endif

vpath %.c $(SRCDIRS)

all: $(DIR) $(DIR)/$(TARGET)

$(DIR)/$(TARGET): $(OBJS) $(LINK_LIBHARU)
	$(LD) -o $@ $(OBJS) $(LINK_LIBHARU) $(LINK_HPDF) $(LDFLAGS)

$(DIR):
	@mkdir -p $(DIR)

$(DIR)/%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

# --- libharu static build rules -------------------------------------

$(LIBHARU_CONFIG): Makefile
	@mkdir -p $(LIBHARU_INC)
	@printf '/* hpdf_config.h -- generated by Makefile.\n' > $@
	@printf ' * libharu built without optional png/zlib support.\n */\n' >> $@

$(LIBHARU_BUILDDIR)/%.o: $(LIBHARU_SRCDIR)/%.c $(LIBHARU_CONFIG)
	@mkdir -p $(LIBHARU_BUILDDIR)
	$(CC) $(CFLAGS) -c -o $@ $<

$(LIBHARU_LIB): $(LIBHARU_OBJS)
	$(AR) rcs $@ $(LIBHARU_OBJS)

clean:
	rm -rf build-release build-debug

# --- verification ---------------------------------------------------
#
# check  performs a clean build of every configured linkage mode and
#        verifies the produced PrinterSegment.  Use CHECK_MODES to run
#        only some modes, e.g.  make check CHECK_MODES=static
CHECK_MODES ?= static dynamic

check: submodule-check $(CHECK_MODES:%=check-%)

check-static:
	@echo "==> check build: static (clean)"
	@$(MAKE) --no-print-directory clean
	@if $(MAKE) --no-print-directory all static=1; then \
	  echo "  static build: OK"; \
	  $(MAKE) --no-print-directory verify-tpd; \
	else \
	  echo "  static build: FAILED"; \
	  exit 1; \
	fi

check-dynamic:
	@echo "==> check build: dynamic (clean)"
	@$(MAKE) --no-print-directory clean
	@if $(MAKE) --no-print-directory all static=0; then \
	  echo "  dynamic build: OK"; \
	  $(MAKE) --no-print-directory verify-tpd; \
	else \
	  echo "  dynamic build: FAILED (is the MorphOS SDK hpdf.library installed?)"; \
	  echo "  use: make check CHECK_MODES=static"; \
	  exit 1; \
	fi

verify-tpd:
	@test -s $(DIR)/$(TARGET) || { echo "FAIL: $(TARGET) is missing or empty"; exit 1; }
	@bytes=$$(od -An -tx1 -j0 -N8 $(DIR)/$(TARGET) | tr -d ' \n'); \
	case "$$bytes" in \
	  0000000070004e75) \
	    echo "  PrinterSegment header (ps_NextSegment + runAlert): OK";; \
	  *) \
	    echo "  FAIL: unexpected header bytes: $$bytes"; \
	    echo "  expected: 00000000 70004e75"; \
	    exit 1;; \
	esac
	@echo "  size: $$(stat -c%s $(DIR)/$(TARGET)) bytes"
	@echo "OK"

submodule-check:
	@test -f external/libharu/include/hpdf.h || \
	  { echo "FAIL: external/libharu not initialized"; \
	    echo "run: git submodule update --init"; \
	    exit 1; }
	@echo "  libharu submodule: OK"

.PHONY: all clean check check-static check-dynamic verify-tpd submodule-check